name: tfgrid_sdk_dart_monorepo
packages:
  - packages/**

scripts:
  analyze:
    run: melos exec -- flutter analyze .
    description: Run `dart analyze` in all packages (linting).
  unit_test:
    run: |
      for package in $(ls packages); do
        if [ "$package" != "stellar_client" ]; then
          cd "packages/$package"
          flutter test --no-pub --coverage
          cd ../..
        fi
      done
    description: Run all Flutter tests in this project except for stellar client.
  unit_test_and_coverage:
    description: Merge all packages coverage trace files ignoring data related to generated files.
    run: |
      melos exec rm -rf coverage
      melos run unit_test
      melos exec -c 1 --file-exists=coverage/lcov.info -- coverde filter --input ./coverage/lcov.info --output MELOS_ROOT_PATH/coverage/filtered.lcov.info --filters \.g\.dart
      coverde value -i coverage/filtered.lcov.info > MELOS_ROOT_PATH/coverage/result.txt
