name: tfgrid_sdk_dart_monorepo
packages:
  - packages/**

scripts:
  analyze:
    run: melos exec -- flutter analyze .
    description: Run `dart analyze` in all packages (linting).
  unit_test:
    run: melos exec --dir-exists="test" --fail-fast -- dart test --concurrency=1
    description: Run all Dart tests in this project sequentially.
  unit_test_and_coverage:
    description: Merge all packages coverage trace files and filter out generated code.
    run: |
      mkdir -p coverage
      melos exec --dir-exists="test" -- dart test --coverage=coverage --concurrency=1
      # Collect all raw .json files from package coverage folders
      find . -name "*.json" -path "*/coverage/*.json" -exec cp {} coverage/ \;
      # Convert to LCOV format
      dart pub global run coverage:format_coverage \
        --lcov \
        --in=coverage \
        --out=coverage/lcov.info \
        --report-on=packages/tfchain_client/lib/generated
      # Filter out generated files
      dart pub global run coverde filter \
        --input coverage/lcov.info \
        --output coverage/filtered.lcov.info \
        --filters .g.dart
        --paths-parent $PWD
      # Print summary report
      dart pub global run coverde value \
        -i coverage/filtered.lcov.info \
        > coverage/result.txt




