name: stellar_client
description: A sample command-line application.
version: 0.1.0

environment:
  sdk: ^3.4.0

# Add regular dependencies here.
dependencies:
  http: ^1.2.2
  stellar_flutter_sdk: ^1.9.2

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.14
  logger: ^2.5.0

scripts:
  test: --coverage=coverage
