name: Analyze

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Repository
        uses: actions/checkout@v3

      - name: Set up FVM
        id: fvm
        uses: kuhnroyal/flutter-fvm-config-action/config@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm.outputs.FLUTTER_VERSION }}
          channel: ${{ steps.fvm.outputs.FLUTTER_CHANNEL }}

      - name: Echo flutter outputs
        run: |
          echo ${{ steps.fvm.outputs }}
          echo ${{ steps.fvm.outcome }}
          echo ${{ steps.fvm.conclusion }}

      - name: Install Melos
        run: /home/runner/work/tfgrid-sdk-dart/.fvm/flutter_sdk/bin/dart pub global activate melos

      - name: Install dependencies
        run: melos bootstrap

      - name: Analyze
        run: dart analyze .
