name: Analyze

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Repository
        uses: actions/checkout@v2

      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1.6.0
        with:
          sdk: "3.2.3"
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.4"    
      - name: Install Melos
        run: dart pub global activate melos

      - name: Install dependencies
        run: dart pub global run melos bootstrap

      - name: Analyze
        run: dart analyze .
