name: Analyze

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Repository
        uses: actions/checkout@v3

      - name: Set up FVM
        id: fvm-config-action
        uses: kuhnroyal/flutter-fvm-config-action/config@v3
        with:
          path: "./.fvmrc"

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
          channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}

      - name: Install Melos
        run: dart pub global activate melos

      - name: Install dependencies
        run: dart pub global run melos bootstrap

      - name: Analyze
        run: dart analyze .
