name: Analyze

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Repository
        uses: actions/checkout@v3

      - name: Set up FVM
        id: fvm-config-action
        uses: kuhnroyal/flutter-fvm-config-action/config@v3
        env:
          DART_SDK_PATH: /home/runner/work/tfgrid-sdk-dart/tfgrid-sdk-dart/.fvm/flutter_sdk/bin/dart

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
          channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}

      - name: Install Melos
        run: $DART_SDK_PATH/bin/dart pub global activate melos

      - name: Install dependencies
        run: $DART_SDK_PATH/bin/dart pub global run melos bootstrap

      - name: Analyze
        run: $DART_SDK_PATH/bin/dart analyze .
