name: Upload Coverage

on:
  pull_request:
    branches:
      - development
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Repository
        uses: actions/checkout@v4
      - name: List Files
        run: ls -R

      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1.6.5
        with:
          sdk: "3.6.1"
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.2"

      - name: Install Melos
        run: dart pub global activate melos

      - name: Install dependencies
        run: melos bootstrap

      - name: Start TFChain Docker Container
        run: |
          sudo docker run -d --network host ghcr.io/threefoldtech/tfchain  --dev --rpc-cors all --rpc-external --rpc-methods=safe
      - name: Wait for TFChain to be ready
        run: |
          while ! nc -z localhost 9944; do
            echo "Waiting for TFChain to be ready..."
            sleep 5
          done

      - name: Run tests and generate coverage with Melos
        run: |
          dart pub global activate coverage
          dart pub global activate coverde
          melos run unit_test_and_coverage
    
      - name: Debug Coverage Directory
        run: ls -lh coverage && head -n 20 coverage/lcov.info || true

      - name: Upload coverage to Codecov
        if: success()
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/filtered.lcov.info
          fail_ci_if_error: true

